name: Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install lua and luarocks
      run: sudo apt install build-essential libreadline-dev unzip lua5.1 luarocks
      
    - name: install busted
      run: sudo luarocks install busted

    - name: Run tests
      run: make tests